import Header from "@/Components/Header/Header";
import type { Metadata } from "next";
import "@/app/global.scss";
import Root from "./Root";

export const metadata: Metadata = {
  title: "Life of code | IT Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Root children={children} />;
}
